
//input ports
add mapped point clk_i clk_i -type PI PI
add mapped point rst_i rst_i -type PI PI
add mapped point opcode_valid_i opcode_valid_i -type PI PI
add mapped point opcode_opcode_i[31] opcode_opcode_i[31] -type PI PI
add mapped point opcode_opcode_i[30] opcode_opcode_i[30] -type PI PI
add mapped point opcode_opcode_i[29] opcode_opcode_i[29] -type PI PI
add mapped point opcode_opcode_i[28] opcode_opcode_i[28] -type PI PI
add mapped point opcode_opcode_i[27] opcode_opcode_i[27] -type PI PI
add mapped point opcode_opcode_i[26] opcode_opcode_i[26] -type PI PI
add mapped point opcode_opcode_i[25] opcode_opcode_i[25] -type PI PI
add mapped point opcode_opcode_i[24] opcode_opcode_i[24] -type PI PI
add mapped point opcode_opcode_i[23] opcode_opcode_i[23] -type PI PI
add mapped point opcode_opcode_i[22] opcode_opcode_i[22] -type PI PI
add mapped point opcode_opcode_i[21] opcode_opcode_i[21] -type PI PI
add mapped point opcode_opcode_i[20] opcode_opcode_i[20] -type PI PI
add mapped point opcode_opcode_i[19] opcode_opcode_i[19] -type PI PI
add mapped point opcode_opcode_i[18] opcode_opcode_i[18] -type PI PI
add mapped point opcode_opcode_i[17] opcode_opcode_i[17] -type PI PI
add mapped point opcode_opcode_i[16] opcode_opcode_i[16] -type PI PI
add mapped point opcode_opcode_i[15] opcode_opcode_i[15] -type PI PI
add mapped point opcode_opcode_i[14] opcode_opcode_i[14] -type PI PI
add mapped point opcode_opcode_i[13] opcode_opcode_i[13] -type PI PI
add mapped point opcode_opcode_i[12] opcode_opcode_i[12] -type PI PI
add mapped point opcode_opcode_i[11] opcode_opcode_i[11] -type PI PI
add mapped point opcode_opcode_i[10] opcode_opcode_i[10] -type PI PI
add mapped point opcode_opcode_i[9] opcode_opcode_i[9] -type PI PI
add mapped point opcode_opcode_i[8] opcode_opcode_i[8] -type PI PI
add mapped point opcode_opcode_i[7] opcode_opcode_i[7] -type PI PI
add mapped point opcode_opcode_i[6] opcode_opcode_i[6] -type PI PI
add mapped point opcode_opcode_i[5] opcode_opcode_i[5] -type PI PI
add mapped point opcode_opcode_i[4] opcode_opcode_i[4] -type PI PI
add mapped point opcode_opcode_i[3] opcode_opcode_i[3] -type PI PI
add mapped point opcode_opcode_i[2] opcode_opcode_i[2] -type PI PI
add mapped point opcode_opcode_i[1] opcode_opcode_i[1] -type PI PI
add mapped point opcode_opcode_i[0] opcode_opcode_i[0] -type PI PI
add mapped point opcode_pc_i[31] opcode_pc_i[31] -type PI PI
add mapped point opcode_pc_i[30] opcode_pc_i[30] -type PI PI
add mapped point opcode_pc_i[29] opcode_pc_i[29] -type PI PI
add mapped point opcode_pc_i[28] opcode_pc_i[28] -type PI PI
add mapped point opcode_pc_i[27] opcode_pc_i[27] -type PI PI
add mapped point opcode_pc_i[26] opcode_pc_i[26] -type PI PI
add mapped point opcode_pc_i[25] opcode_pc_i[25] -type PI PI
add mapped point opcode_pc_i[24] opcode_pc_i[24] -type PI PI
add mapped point opcode_pc_i[23] opcode_pc_i[23] -type PI PI
add mapped point opcode_pc_i[22] opcode_pc_i[22] -type PI PI
add mapped point opcode_pc_i[21] opcode_pc_i[21] -type PI PI
add mapped point opcode_pc_i[20] opcode_pc_i[20] -type PI PI
add mapped point opcode_pc_i[19] opcode_pc_i[19] -type PI PI
add mapped point opcode_pc_i[18] opcode_pc_i[18] -type PI PI
add mapped point opcode_pc_i[17] opcode_pc_i[17] -type PI PI
add mapped point opcode_pc_i[16] opcode_pc_i[16] -type PI PI
add mapped point opcode_pc_i[15] opcode_pc_i[15] -type PI PI
add mapped point opcode_pc_i[14] opcode_pc_i[14] -type PI PI
add mapped point opcode_pc_i[13] opcode_pc_i[13] -type PI PI
add mapped point opcode_pc_i[12] opcode_pc_i[12] -type PI PI
add mapped point opcode_pc_i[11] opcode_pc_i[11] -type PI PI
add mapped point opcode_pc_i[10] opcode_pc_i[10] -type PI PI
add mapped point opcode_pc_i[9] opcode_pc_i[9] -type PI PI
add mapped point opcode_pc_i[8] opcode_pc_i[8] -type PI PI
add mapped point opcode_pc_i[7] opcode_pc_i[7] -type PI PI
add mapped point opcode_pc_i[6] opcode_pc_i[6] -type PI PI
add mapped point opcode_pc_i[5] opcode_pc_i[5] -type PI PI
add mapped point opcode_pc_i[4] opcode_pc_i[4] -type PI PI
add mapped point opcode_pc_i[3] opcode_pc_i[3] -type PI PI
add mapped point opcode_pc_i[2] opcode_pc_i[2] -type PI PI
add mapped point opcode_pc_i[1] opcode_pc_i[1] -type PI PI
add mapped point opcode_pc_i[0] opcode_pc_i[0] -type PI PI
add mapped point opcode_invalid_i opcode_invalid_i -type PI PI
add mapped point opcode_rd_idx_i[4] opcode_rd_idx_i[4] -type PI PI
add mapped point opcode_rd_idx_i[3] opcode_rd_idx_i[3] -type PI PI
add mapped point opcode_rd_idx_i[2] opcode_rd_idx_i[2] -type PI PI
add mapped point opcode_rd_idx_i[1] opcode_rd_idx_i[1] -type PI PI
add mapped point opcode_rd_idx_i[0] opcode_rd_idx_i[0] -type PI PI
add mapped point opcode_ra_idx_i[4] opcode_ra_idx_i[4] -type PI PI
add mapped point opcode_ra_idx_i[3] opcode_ra_idx_i[3] -type PI PI
add mapped point opcode_ra_idx_i[2] opcode_ra_idx_i[2] -type PI PI
add mapped point opcode_ra_idx_i[1] opcode_ra_idx_i[1] -type PI PI
add mapped point opcode_ra_idx_i[0] opcode_ra_idx_i[0] -type PI PI
add mapped point opcode_rb_idx_i[4] opcode_rb_idx_i[4] -type PI PI
add mapped point opcode_rb_idx_i[3] opcode_rb_idx_i[3] -type PI PI
add mapped point opcode_rb_idx_i[2] opcode_rb_idx_i[2] -type PI PI
add mapped point opcode_rb_idx_i[1] opcode_rb_idx_i[1] -type PI PI
add mapped point opcode_rb_idx_i[0] opcode_rb_idx_i[0] -type PI PI
add mapped point opcode_ra_operand_i[31] opcode_ra_operand_i[31] -type PI PI
add mapped point opcode_ra_operand_i[30] opcode_ra_operand_i[30] -type PI PI
add mapped point opcode_ra_operand_i[29] opcode_ra_operand_i[29] -type PI PI
add mapped point opcode_ra_operand_i[28] opcode_ra_operand_i[28] -type PI PI
add mapped point opcode_ra_operand_i[27] opcode_ra_operand_i[27] -type PI PI
add mapped point opcode_ra_operand_i[26] opcode_ra_operand_i[26] -type PI PI
add mapped point opcode_ra_operand_i[25] opcode_ra_operand_i[25] -type PI PI
add mapped point opcode_ra_operand_i[24] opcode_ra_operand_i[24] -type PI PI
add mapped point opcode_ra_operand_i[23] opcode_ra_operand_i[23] -type PI PI
add mapped point opcode_ra_operand_i[22] opcode_ra_operand_i[22] -type PI PI
add mapped point opcode_ra_operand_i[21] opcode_ra_operand_i[21] -type PI PI
add mapped point opcode_ra_operand_i[20] opcode_ra_operand_i[20] -type PI PI
add mapped point opcode_ra_operand_i[19] opcode_ra_operand_i[19] -type PI PI
add mapped point opcode_ra_operand_i[18] opcode_ra_operand_i[18] -type PI PI
add mapped point opcode_ra_operand_i[17] opcode_ra_operand_i[17] -type PI PI
add mapped point opcode_ra_operand_i[16] opcode_ra_operand_i[16] -type PI PI
add mapped point opcode_ra_operand_i[15] opcode_ra_operand_i[15] -type PI PI
add mapped point opcode_ra_operand_i[14] opcode_ra_operand_i[14] -type PI PI
add mapped point opcode_ra_operand_i[13] opcode_ra_operand_i[13] -type PI PI
add mapped point opcode_ra_operand_i[12] opcode_ra_operand_i[12] -type PI PI
add mapped point opcode_ra_operand_i[11] opcode_ra_operand_i[11] -type PI PI
add mapped point opcode_ra_operand_i[10] opcode_ra_operand_i[10] -type PI PI
add mapped point opcode_ra_operand_i[9] opcode_ra_operand_i[9] -type PI PI
add mapped point opcode_ra_operand_i[8] opcode_ra_operand_i[8] -type PI PI
add mapped point opcode_ra_operand_i[7] opcode_ra_operand_i[7] -type PI PI
add mapped point opcode_ra_operand_i[6] opcode_ra_operand_i[6] -type PI PI
add mapped point opcode_ra_operand_i[5] opcode_ra_operand_i[5] -type PI PI
add mapped point opcode_ra_operand_i[4] opcode_ra_operand_i[4] -type PI PI
add mapped point opcode_ra_operand_i[3] opcode_ra_operand_i[3] -type PI PI
add mapped point opcode_ra_operand_i[2] opcode_ra_operand_i[2] -type PI PI
add mapped point opcode_ra_operand_i[1] opcode_ra_operand_i[1] -type PI PI
add mapped point opcode_ra_operand_i[0] opcode_ra_operand_i[0] -type PI PI
add mapped point opcode_rb_operand_i[31] opcode_rb_operand_i[31] -type PI PI
add mapped point opcode_rb_operand_i[30] opcode_rb_operand_i[30] -type PI PI
add mapped point opcode_rb_operand_i[29] opcode_rb_operand_i[29] -type PI PI
add mapped point opcode_rb_operand_i[28] opcode_rb_operand_i[28] -type PI PI
add mapped point opcode_rb_operand_i[27] opcode_rb_operand_i[27] -type PI PI
add mapped point opcode_rb_operand_i[26] opcode_rb_operand_i[26] -type PI PI
add mapped point opcode_rb_operand_i[25] opcode_rb_operand_i[25] -type PI PI
add mapped point opcode_rb_operand_i[24] opcode_rb_operand_i[24] -type PI PI
add mapped point opcode_rb_operand_i[23] opcode_rb_operand_i[23] -type PI PI
add mapped point opcode_rb_operand_i[22] opcode_rb_operand_i[22] -type PI PI
add mapped point opcode_rb_operand_i[21] opcode_rb_operand_i[21] -type PI PI
add mapped point opcode_rb_operand_i[20] opcode_rb_operand_i[20] -type PI PI
add mapped point opcode_rb_operand_i[19] opcode_rb_operand_i[19] -type PI PI
add mapped point opcode_rb_operand_i[18] opcode_rb_operand_i[18] -type PI PI
add mapped point opcode_rb_operand_i[17] opcode_rb_operand_i[17] -type PI PI
add mapped point opcode_rb_operand_i[16] opcode_rb_operand_i[16] -type PI PI
add mapped point opcode_rb_operand_i[15] opcode_rb_operand_i[15] -type PI PI
add mapped point opcode_rb_operand_i[14] opcode_rb_operand_i[14] -type PI PI
add mapped point opcode_rb_operand_i[13] opcode_rb_operand_i[13] -type PI PI
add mapped point opcode_rb_operand_i[12] opcode_rb_operand_i[12] -type PI PI
add mapped point opcode_rb_operand_i[11] opcode_rb_operand_i[11] -type PI PI
add mapped point opcode_rb_operand_i[10] opcode_rb_operand_i[10] -type PI PI
add mapped point opcode_rb_operand_i[9] opcode_rb_operand_i[9] -type PI PI
add mapped point opcode_rb_operand_i[8] opcode_rb_operand_i[8] -type PI PI
add mapped point opcode_rb_operand_i[7] opcode_rb_operand_i[7] -type PI PI
add mapped point opcode_rb_operand_i[6] opcode_rb_operand_i[6] -type PI PI
add mapped point opcode_rb_operand_i[5] opcode_rb_operand_i[5] -type PI PI
add mapped point opcode_rb_operand_i[4] opcode_rb_operand_i[4] -type PI PI
add mapped point opcode_rb_operand_i[3] opcode_rb_operand_i[3] -type PI PI
add mapped point opcode_rb_operand_i[2] opcode_rb_operand_i[2] -type PI PI
add mapped point opcode_rb_operand_i[1] opcode_rb_operand_i[1] -type PI PI
add mapped point opcode_rb_operand_i[0] opcode_rb_operand_i[0] -type PI PI

//output ports
add mapped point writeback_valid_o writeback_valid_o -type PO PO
add mapped point writeback_value_o[31] writeback_value_o[31] -type PO PO
add mapped point writeback_value_o[30] writeback_value_o[30] -type PO PO
add mapped point writeback_value_o[29] writeback_value_o[29] -type PO PO
add mapped point writeback_value_o[28] writeback_value_o[28] -type PO PO
add mapped point writeback_value_o[27] writeback_value_o[27] -type PO PO
add mapped point writeback_value_o[26] writeback_value_o[26] -type PO PO
add mapped point writeback_value_o[25] writeback_value_o[25] -type PO PO
add mapped point writeback_value_o[24] writeback_value_o[24] -type PO PO
add mapped point writeback_value_o[23] writeback_value_o[23] -type PO PO
add mapped point writeback_value_o[22] writeback_value_o[22] -type PO PO
add mapped point writeback_value_o[21] writeback_value_o[21] -type PO PO
add mapped point writeback_value_o[20] writeback_value_o[20] -type PO PO
add mapped point writeback_value_o[19] writeback_value_o[19] -type PO PO
add mapped point writeback_value_o[18] writeback_value_o[18] -type PO PO
add mapped point writeback_value_o[17] writeback_value_o[17] -type PO PO
add mapped point writeback_value_o[16] writeback_value_o[16] -type PO PO
add mapped point writeback_value_o[15] writeback_value_o[15] -type PO PO
add mapped point writeback_value_o[14] writeback_value_o[14] -type PO PO
add mapped point writeback_value_o[13] writeback_value_o[13] -type PO PO
add mapped point writeback_value_o[12] writeback_value_o[12] -type PO PO
add mapped point writeback_value_o[11] writeback_value_o[11] -type PO PO
add mapped point writeback_value_o[10] writeback_value_o[10] -type PO PO
add mapped point writeback_value_o[9] writeback_value_o[9] -type PO PO
add mapped point writeback_value_o[8] writeback_value_o[8] -type PO PO
add mapped point writeback_value_o[7] writeback_value_o[7] -type PO PO
add mapped point writeback_value_o[6] writeback_value_o[6] -type PO PO
add mapped point writeback_value_o[5] writeback_value_o[5] -type PO PO
add mapped point writeback_value_o[4] writeback_value_o[4] -type PO PO
add mapped point writeback_value_o[3] writeback_value_o[3] -type PO PO
add mapped point writeback_value_o[2] writeback_value_o[2] -type PO PO
add mapped point writeback_value_o[1] writeback_value_o[1] -type PO PO
add mapped point writeback_value_o[0] writeback_value_o[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point div_prepare_q/q div_prepare_q_reg/Q -type DFF DFF
add mapped point valid_q/q valid_q_reg/Q -type DFF DFF
add mapped point div_busy_q/q div_busy_q_reg/Q -type DFF DFF
add mapped point div_calc_clz_q/q div_calc_clz_q_reg/Q -type DFF DFF
add mapped point div_inst_q/q div_inst_q_reg/Q -type DFF DFF
add mapped point dividend_q[0]/q dividend_q_reg[0]/Q -type DFF DFF
add mapped point dividend_q[1]/q dividend_q_reg[1]/Q -type DFF DFF
add mapped point dividend_q[2]/q dividend_q_reg[2]/Q -type DFF DFF
add mapped point dividend_q[3]/q dividend_q_reg[3]/Q -type DFF DFF
add mapped point dividend_q[4]/q dividend_q_reg[4]/Q -type DFF DFF
add mapped point dividend_q[5]/q dividend_q_reg[5]/Q -type DFF DFF
add mapped point dividend_q[6]/q dividend_q_reg[6]/Q -type DFF DFF
add mapped point dividend_q[7]/q dividend_q_reg[7]/Q -type DFF DFF
add mapped point dividend_q[8]/q dividend_q_reg[8]/Q -type DFF DFF
add mapped point dividend_q[9]/q dividend_q_reg[9]/Q -type DFF DFF
add mapped point dividend_q[10]/q dividend_q_reg[10]/Q -type DFF DFF
add mapped point dividend_q[11]/q dividend_q_reg[11]/Q -type DFF DFF
add mapped point dividend_q[12]/q dividend_q_reg[12]/Q -type DFF DFF
add mapped point dividend_q[13]/q dividend_q_reg[13]/Q -type DFF DFF
add mapped point dividend_q[14]/q dividend_q_reg[14]/Q -type DFF DFF
add mapped point dividend_q[15]/q dividend_q_reg[15]/Q -type DFF DFF
add mapped point dividend_q[16]/q dividend_q_reg[16]/Q -type DFF DFF
add mapped point dividend_q[17]/q dividend_q_reg[17]/Q -type DFF DFF
add mapped point dividend_q[18]/q dividend_q_reg[18]/Q -type DFF DFF
add mapped point dividend_q[19]/q dividend_q_reg[19]/Q -type DFF DFF
add mapped point dividend_q[20]/q dividend_q_reg[20]/Q -type DFF DFF
add mapped point dividend_q[21]/q dividend_q_reg[21]/Q -type DFF DFF
add mapped point dividend_q[22]/q dividend_q_reg[22]/Q -type DFF DFF
add mapped point dividend_q[23]/q dividend_q_reg[23]/Q -type DFF DFF
add mapped point dividend_q[24]/q dividend_q_reg[24]/Q -type DFF DFF
add mapped point dividend_q[25]/q dividend_q_reg[25]/Q -type DFF DFF
add mapped point dividend_q[26]/q dividend_q_reg[26]/Q -type DFF DFF
add mapped point dividend_q[27]/q dividend_q_reg[27]/Q -type DFF DFF
add mapped point dividend_q[28]/q dividend_q_reg[28]/Q -type DFF DFF
add mapped point dividend_q[29]/q dividend_q_reg[29]/Q -type DFF DFF
add mapped point dividend_q[30]/q dividend_q_reg[30]/Q -type DFF DFF
add mapped point dividend_q[31]/q dividend_q_reg[31]/Q -type DFF DFF
add mapped point divisor_q[4]/q divisor_q_reg[4]/Q -type DFF DFF
add mapped point divisor_q[6]/q divisor_q_reg[6]/Q -type DFF DFF
add mapped point divisor_q[7]/q divisor_q_reg[7]/Q -type DFF DFF
add mapped point divisor_q[8]/q divisor_q_reg[8]/Q -type DFF DFF
add mapped point divisor_q[9]/q divisor_q_reg[9]/Q -type DFF DFF
add mapped point divisor_q[10]/q divisor_q_reg[10]/Q -type DFF DFF
add mapped point divisor_q[12]/q divisor_q_reg[12]/Q -type DFF DFF
add mapped point divisor_q[13]/q divisor_q_reg[13]/Q -type DFF DFF
add mapped point divisor_q[14]/q divisor_q_reg[14]/Q -type DFF DFF
add mapped point divisor_q[16]/q divisor_q_reg[16]/Q -type DFF DFF
add mapped point divisor_q[18]/q divisor_q_reg[18]/Q -type DFF DFF
add mapped point divisor_q[19]/q divisor_q_reg[19]/Q -type DFF DFF
add mapped point divisor_q[20]/q divisor_q_reg[20]/Q -type DFF DFF
add mapped point divisor_q[21]/q divisor_q_reg[21]/Q -type DFF DFF
add mapped point divisor_q[23]/q divisor_q_reg[23]/Q -type DFF DFF
add mapped point divisor_q[24]/q divisor_q_reg[24]/Q -type DFF DFF
add mapped point divisor_q[26]/q divisor_q_reg[26]/Q -type DFF DFF
add mapped point divisor_q[28]/q divisor_q_reg[28]/Q -type DFF DFF
add mapped point divisor_q[29]/q divisor_q_reg[29]/Q -type DFF DFF
add mapped point divisor_q[30]/q divisor_q_reg[30]/Q -type DFF DFF
add mapped point divisor_q[31]/q divisor_q_reg[31]/Q -type DFF DFF
add mapped point divisor_q[32]/q divisor_q_reg[32]/Q -type DFF DFF
add mapped point divisor_q[33]/q divisor_q_reg[33]/Q -type DFF DFF
add mapped point divisor_q[34]/q divisor_q_reg[34]/Q -type DFF DFF
add mapped point divisor_q[35]/q divisor_q_reg[35]/Q -type DFF DFF
add mapped point divisor_q[36]/q divisor_q_reg[36]/Q -type DFF DFF
add mapped point divisor_q[37]/q divisor_q_reg[37]/Q -type DFF DFF
add mapped point divisor_q[38]/q divisor_q_reg[38]/Q -type DFF DFF
add mapped point divisor_q[39]/q divisor_q_reg[39]/Q -type DFF DFF
add mapped point divisor_q[40]/q divisor_q_reg[40]/Q -type DFF DFF
add mapped point divisor_q[41]/q divisor_q_reg[41]/Q -type DFF DFF
add mapped point divisor_q[42]/q divisor_q_reg[42]/Q -type DFF DFF
add mapped point divisor_q[43]/q divisor_q_reg[43]/Q -type DFF DFF
add mapped point divisor_q[44]/q divisor_q_reg[44]/Q -type DFF DFF
add mapped point divisor_q[45]/q divisor_q_reg[45]/Q -type DFF DFF
add mapped point divisor_q[46]/q divisor_q_reg[46]/Q -type DFF DFF
add mapped point divisor_q[47]/q divisor_q_reg[47]/Q -type DFF DFF
add mapped point divisor_q[48]/q divisor_q_reg[48]/Q -type DFF DFF
add mapped point divisor_q[49]/q divisor_q_reg[49]/Q -type DFF DFF
add mapped point divisor_q[50]/q divisor_q_reg[50]/Q -type DFF DFF
add mapped point divisor_q[51]/q divisor_q_reg[51]/Q -type DFF DFF
add mapped point divisor_q[52]/q divisor_q_reg[52]/Q -type DFF DFF
add mapped point divisor_q[53]/q divisor_q_reg[53]/Q -type DFF DFF
add mapped point divisor_q[54]/q divisor_q_reg[54]/Q -type DFF DFF
add mapped point divisor_q[55]/q divisor_q_reg[55]/Q -type DFF DFF
add mapped point divisor_q[56]/q divisor_q_reg[56]/Q -type DFF DFF
add mapped point divisor_q[57]/q divisor_q_reg[57]/Q -type DFF DFF
add mapped point divisor_q[58]/q divisor_q_reg[58]/Q -type DFF DFF
add mapped point divisor_q[59]/q divisor_q_reg[59]/Q -type DFF DFF
add mapped point divisor_q[60]/q divisor_q_reg[60]/Q -type DFF DFF
add mapped point divisor_q[61]/q divisor_q_reg[61]/Q -type DFF DFF
add mapped point divisor_q[62]/q divisor_q_reg[62]/Q -type DFF DFF
add mapped point invert_res_q/q invert_res_q_reg/Q -type DFF DFF
add mapped point last_a_q[0]/q last_a_q_reg[0]/Q -type DFF DFF
add mapped point last_a_q[1]/q last_a_q_reg[1]/Q -type DFF DFF
add mapped point last_a_q[2]/q last_a_q_reg[2]/Q -type DFF DFF
add mapped point last_a_q[3]/q last_a_q_reg[3]/Q -type DFF DFF
add mapped point last_a_q[4]/q last_a_q_reg[4]/Q -type DFF DFF
add mapped point last_a_q[5]/q last_a_q_reg[5]/Q -type DFF DFF
add mapped point last_a_q[6]/q last_a_q_reg[6]/Q -type DFF DFF
add mapped point last_a_q[7]/q last_a_q_reg[7]/Q -type DFF DFF
add mapped point last_a_q[8]/q last_a_q_reg[8]/Q -type DFF DFF
add mapped point last_a_q[9]/q last_a_q_reg[9]/Q -type DFF DFF
add mapped point last_a_q[10]/q last_a_q_reg[10]/Q -type DFF DFF
add mapped point last_a_q[11]/q last_a_q_reg[11]/Q -type DFF DFF
add mapped point last_a_q[12]/q last_a_q_reg[12]/Q -type DFF DFF
add mapped point last_a_q[13]/q last_a_q_reg[13]/Q -type DFF DFF
add mapped point last_a_q[14]/q last_a_q_reg[14]/Q -type DFF DFF
add mapped point last_a_q[15]/q last_a_q_reg[15]/Q -type DFF DFF
add mapped point last_a_q[16]/q last_a_q_reg[16]/Q -type DFF DFF
add mapped point last_a_q[17]/q last_a_q_reg[17]/Q -type DFF DFF
add mapped point last_a_q[18]/q last_a_q_reg[18]/Q -type DFF DFF
add mapped point last_a_q[19]/q last_a_q_reg[19]/Q -type DFF DFF
add mapped point last_a_q[20]/q last_a_q_reg[20]/Q -type DFF DFF
add mapped point last_a_q[21]/q last_a_q_reg[21]/Q -type DFF DFF
add mapped point last_a_q[22]/q last_a_q_reg[22]/Q -type DFF DFF
add mapped point last_a_q[23]/q last_a_q_reg[23]/Q -type DFF DFF
add mapped point last_a_q[24]/q last_a_q_reg[24]/Q -type DFF DFF
add mapped point last_a_q[25]/q last_a_q_reg[25]/Q -type DFF DFF
add mapped point last_a_q[26]/q last_a_q_reg[26]/Q -type DFF DFF
add mapped point last_a_q[27]/q last_a_q_reg[27]/Q -type DFF DFF
add mapped point last_a_q[28]/q last_a_q_reg[28]/Q -type DFF DFF
add mapped point last_a_q[30]/q last_a_q_reg[30]/Q -type DFF DFF
add mapped point last_a_q[31]/q last_a_q_reg[31]/Q -type DFF DFF
add mapped point last_b_q[0]/q last_b_q_reg[0]/Q -type DFF DFF
add mapped point last_b_q[1]/q last_b_q_reg[1]/Q -type DFF DFF
add mapped point last_b_q[2]/q last_b_q_reg[2]/Q -type DFF DFF
add mapped point last_b_q[3]/q last_b_q_reg[3]/Q -type DFF DFF
add mapped point last_b_q[4]/q last_b_q_reg[4]/Q -type DFF DFF
add mapped point last_b_q[5]/q last_b_q_reg[5]/Q -type DFF DFF
add mapped point last_b_q[6]/q last_b_q_reg[6]/Q -type DFF DFF
add mapped point last_b_q[7]/q last_b_q_reg[7]/Q -type DFF DFF
add mapped point last_b_q[8]/q last_b_q_reg[8]/Q -type DFF DFF
add mapped point last_b_q[9]/q last_b_q_reg[9]/Q -type DFF DFF
add mapped point last_b_q[10]/q last_b_q_reg[10]/Q -type DFF DFF
add mapped point last_b_q[11]/q last_b_q_reg[11]/Q -type DFF DFF
add mapped point last_b_q[12]/q last_b_q_reg[12]/Q -type DFF DFF
add mapped point last_b_q[13]/q last_b_q_reg[13]/Q -type DFF DFF
add mapped point last_b_q[14]/q last_b_q_reg[14]/Q -type DFF DFF
add mapped point last_b_q[15]/q last_b_q_reg[15]/Q -type DFF DFF
add mapped point last_b_q[16]/q last_b_q_reg[16]/Q -type DFF DFF
add mapped point last_b_q[17]/q last_b_q_reg[17]/Q -type DFF DFF
add mapped point last_b_q[18]/q last_b_q_reg[18]/Q -type DFF DFF
add mapped point last_b_q[19]/q last_b_q_reg[19]/Q -type DFF DFF
add mapped point last_b_q[20]/q last_b_q_reg[20]/Q -type DFF DFF
add mapped point last_b_q[21]/q last_b_q_reg[21]/Q -type DFF DFF
add mapped point last_b_q[22]/q last_b_q_reg[22]/Q -type DFF DFF
add mapped point last_b_q[23]/q last_b_q_reg[23]/Q -type DFF DFF
add mapped point last_b_q[24]/q last_b_q_reg[24]/Q -type DFF DFF
add mapped point last_b_q[25]/q last_b_q_reg[25]/Q -type DFF DFF
add mapped point last_b_q[26]/q last_b_q_reg[26]/Q -type DFF DFF
add mapped point last_b_q[27]/q last_b_q_reg[27]/Q -type DFF DFF
add mapped point last_b_q[28]/q last_b_q_reg[28]/Q -type DFF DFF
add mapped point last_b_q[29]/q last_b_q_reg[29]/Q -type DFF DFF
add mapped point last_b_q[30]/q last_b_q_reg[30]/Q -type DFF DFF
add mapped point last_b_q[31]/q last_b_q_reg[31]/Q -type DFF DFF
add mapped point last_div_q/q last_div_q_reg/Q -type DFF DFF
add mapped point last_divu_q/q last_divu_q_reg/Q -type DFF DFF
add mapped point last_rem_q/q last_rem_q_reg/Q -type DFF DFF
add mapped point last_remu_q/q last_remu_q_reg/Q -type DFF DFF
add mapped point op_a_abs_r[0]/q op_a_abs_r_reg[0]/Q -type DFF DFF
add mapped point op_a_abs_r[1]/q op_a_abs_r_reg[1]/Q -type DFF DFF
add mapped point op_a_abs_r[2]/q op_a_abs_r_reg[2]/Q -type DFF DFF
add mapped point op_a_abs_r[3]/q op_a_abs_r_reg[3]/Q -type DFF DFF
add mapped point op_a_abs_r[4]/q op_a_abs_r_reg[4]/Q -type DFF DFF
add mapped point op_a_abs_r[8]/q op_a_abs_r_reg[8]/Q -type DFF DFF
add mapped point op_a_abs_r[9]/q op_a_abs_r_reg[9]/Q -type DFF DFF
add mapped point op_a_abs_r[10]/q op_a_abs_r_reg[10]/Q -type DFF DFF
add mapped point op_a_abs_r[11]/q op_a_abs_r_reg[11]/Q -type DFF DFF
add mapped point op_a_abs_r[12]/q op_a_abs_r_reg[12]/Q -type DFF DFF
add mapped point op_a_abs_r[14]/q op_a_abs_r_reg[14]/Q -type DFF DFF
add mapped point op_a_abs_r[16]/q op_a_abs_r_reg[16]/Q -type DFF DFF
add mapped point op_a_abs_r[17]/q op_a_abs_r_reg[17]/Q -type DFF DFF
add mapped point op_a_abs_r[18]/q op_a_abs_r_reg[18]/Q -type DFF DFF
add mapped point op_a_abs_r[19]/q op_a_abs_r_reg[19]/Q -type DFF DFF
add mapped point op_a_abs_r[20]/q op_a_abs_r_reg[20]/Q -type DFF DFF
add mapped point op_a_abs_r[21]/q op_a_abs_r_reg[21]/Q -type DFF DFF
add mapped point op_a_abs_r[22]/q op_a_abs_r_reg[22]/Q -type DFF DFF
add mapped point op_a_abs_r[23]/q op_a_abs_r_reg[23]/Q -type DFF DFF
add mapped point op_a_abs_r[24]/q op_a_abs_r_reg[24]/Q -type DFF DFF
add mapped point op_a_abs_r[25]/q op_a_abs_r_reg[25]/Q -type DFF DFF
add mapped point op_a_abs_r[26]/q op_a_abs_r_reg[26]/Q -type DFF DFF
add mapped point op_a_abs_r[27]/q op_a_abs_r_reg[27]/Q -type DFF DFF
add mapped point op_a_abs_r[28]/q op_a_abs_r_reg[28]/Q -type DFF DFF
add mapped point op_a_abs_r[29]/q op_a_abs_r_reg[29]/Q -type DFF DFF
add mapped point op_a_abs_r[30]/q op_a_abs_r_reg[30]/Q -type DFF DFF
add mapped point op_a_abs_r[31]/q op_a_abs_r_reg[31]/Q -type DFF DFF
add mapped point op_b_abs_r[0]/q op_b_abs_r_reg[0]/Q -type DFF DFF
add mapped point op_b_abs_r[3]/q op_b_abs_r_reg[3]/Q -type DFF DFF
add mapped point op_b_abs_r[4]/q op_b_abs_r_reg[4]/Q -type DFF DFF
add mapped point op_b_abs_r[5]/q op_b_abs_r_reg[5]/Q -type DFF DFF
add mapped point op_b_abs_r[7]/q op_b_abs_r_reg[7]/Q -type DFF DFF
add mapped point op_b_abs_r[8]/q op_b_abs_r_reg[8]/Q -type DFF DFF
add mapped point op_b_abs_r[9]/q op_b_abs_r_reg[9]/Q -type DFF DFF
add mapped point op_b_abs_r[10]/q op_b_abs_r_reg[10]/Q -type DFF DFF
add mapped point op_b_abs_r[11]/q op_b_abs_r_reg[11]/Q -type DFF DFF
add mapped point op_b_abs_r[12]/q op_b_abs_r_reg[12]/Q -type DFF DFF
add mapped point op_b_abs_r[15]/q op_b_abs_r_reg[15]/Q -type DFF DFF
add mapped point op_b_abs_r[16]/q op_b_abs_r_reg[16]/Q -type DFF DFF
add mapped point op_b_abs_r[17]/q op_b_abs_r_reg[17]/Q -type DFF DFF
add mapped point op_b_abs_r[19]/q op_b_abs_r_reg[19]/Q -type DFF DFF
add mapped point op_b_abs_r[21]/q op_b_abs_r_reg[21]/Q -type DFF DFF
add mapped point op_b_abs_r[23]/q op_b_abs_r_reg[23]/Q -type DFF DFF
add mapped point op_b_abs_r[27]/q op_b_abs_r_reg[27]/Q -type DFF DFF
add mapped point op_b_abs_r[28]/q op_b_abs_r_reg[28]/Q -type DFF DFF
add mapped point op_b_abs_r[29]/q op_b_abs_r_reg[29]/Q -type DFF DFF
add mapped point q_mask_q[0]/q q_mask_q_reg[0]/Q -type DFF DFF
add mapped point q_mask_q[1]/q q_mask_q_reg[1]/Q -type DFF DFF
add mapped point q_mask_q[2]/q q_mask_q_reg[2]/Q -type DFF DFF
add mapped point q_mask_q[3]/q q_mask_q_reg[3]/Q -type DFF DFF
add mapped point q_mask_q[4]/q q_mask_q_reg[4]/Q -type DFF DFF
add mapped point q_mask_q[5]/q q_mask_q_reg[5]/Q -type DFF DFF
add mapped point q_mask_q[6]/q q_mask_q_reg[6]/Q -type DFF DFF
add mapped point q_mask_q[7]/q q_mask_q_reg[7]/Q -type DFF DFF
add mapped point q_mask_q[8]/q q_mask_q_reg[8]/Q -type DFF DFF
add mapped point q_mask_q[9]/q q_mask_q_reg[9]/Q -type DFF DFF
add mapped point q_mask_q[10]/q q_mask_q_reg[10]/Q -type DFF DFF
add mapped point q_mask_q[11]/q q_mask_q_reg[11]/Q -type DFF DFF
add mapped point q_mask_q[12]/q q_mask_q_reg[12]/Q -type DFF DFF
add mapped point q_mask_q[13]/q q_mask_q_reg[13]/Q -type DFF DFF
add mapped point q_mask_q[14]/q q_mask_q_reg[14]/Q -type DFF DFF
add mapped point q_mask_q[15]/q q_mask_q_reg[15]/Q -type DFF DFF
add mapped point q_mask_q[16]/q q_mask_q_reg[16]/Q -type DFF DFF
add mapped point q_mask_q[17]/q q_mask_q_reg[17]/Q -type DFF DFF
add mapped point q_mask_q[18]/q q_mask_q_reg[18]/Q -type DFF DFF
add mapped point q_mask_q[19]/q q_mask_q_reg[19]/Q -type DFF DFF
add mapped point q_mask_q[20]/q q_mask_q_reg[20]/Q -type DFF DFF
add mapped point q_mask_q[21]/q q_mask_q_reg[21]/Q -type DFF DFF
add mapped point q_mask_q[22]/q q_mask_q_reg[22]/Q -type DFF DFF
add mapped point q_mask_q[23]/q q_mask_q_reg[23]/Q -type DFF DFF
add mapped point q_mask_q[24]/q q_mask_q_reg[24]/Q -type DFF DFF
add mapped point q_mask_q[25]/q q_mask_q_reg[25]/Q -type DFF DFF
add mapped point q_mask_q[26]/q q_mask_q_reg[26]/Q -type DFF DFF
add mapped point q_mask_q[27]/q q_mask_q_reg[27]/Q -type DFF DFF
add mapped point q_mask_q[28]/q q_mask_q_reg[28]/Q -type DFF DFF
add mapped point q_mask_q[29]/q q_mask_q_reg[29]/Q -type DFF DFF
add mapped point q_mask_q[30]/q q_mask_q_reg[30]/Q -type DFF DFF
add mapped point q_mask_q[31]/q q_mask_q_reg[31]/Q -type DFF DFF
add mapped point quotient_q[0]/q quotient_q_reg[0]/Q -type DFF DFF
add mapped point quotient_q[1]/q quotient_q_reg[1]/Q -type DFF DFF
add mapped point quotient_q[2]/q quotient_q_reg[2]/Q -type DFF DFF
add mapped point quotient_q[3]/q quotient_q_reg[3]/Q -type DFF DFF
add mapped point quotient_q[4]/q quotient_q_reg[4]/Q -type DFF DFF
add mapped point quotient_q[5]/q quotient_q_reg[5]/Q -type DFF DFF
add mapped point quotient_q[6]/q quotient_q_reg[6]/Q -type DFF DFF
add mapped point quotient_q[7]/q quotient_q_reg[7]/Q -type DFF DFF
add mapped point quotient_q[8]/q quotient_q_reg[8]/Q -type DFF DFF
add mapped point quotient_q[9]/q quotient_q_reg[9]/Q -type DFF DFF
add mapped point quotient_q[10]/q quotient_q_reg[10]/Q -type DFF DFF
add mapped point quotient_q[11]/q quotient_q_reg[11]/Q -type DFF DFF
add mapped point quotient_q[12]/q quotient_q_reg[12]/Q -type DFF DFF
add mapped point quotient_q[13]/q quotient_q_reg[13]/Q -type DFF DFF
add mapped point quotient_q[14]/q quotient_q_reg[14]/Q -type DFF DFF
add mapped point quotient_q[15]/q quotient_q_reg[15]/Q -type DFF DFF
add mapped point quotient_q[16]/q quotient_q_reg[16]/Q -type DFF DFF
add mapped point quotient_q[17]/q quotient_q_reg[17]/Q -type DFF DFF
add mapped point quotient_q[18]/q quotient_q_reg[18]/Q -type DFF DFF
add mapped point quotient_q[19]/q quotient_q_reg[19]/Q -type DFF DFF
add mapped point quotient_q[20]/q quotient_q_reg[20]/Q -type DFF DFF
add mapped point quotient_q[21]/q quotient_q_reg[21]/Q -type DFF DFF
add mapped point quotient_q[22]/q quotient_q_reg[22]/Q -type DFF DFF
add mapped point quotient_q[23]/q quotient_q_reg[23]/Q -type DFF DFF
add mapped point quotient_q[24]/q quotient_q_reg[24]/Q -type DFF DFF
add mapped point quotient_q[25]/q quotient_q_reg[25]/Q -type DFF DFF
add mapped point quotient_q[26]/q quotient_q_reg[26]/Q -type DFF DFF
add mapped point quotient_q[27]/q quotient_q_reg[27]/Q -type DFF DFF
add mapped point quotient_q[28]/q quotient_q_reg[28]/Q -type DFF DFF
add mapped point quotient_q[29]/q quotient_q_reg[29]/Q -type DFF DFF
add mapped point quotient_q[30]/q quotient_q_reg[30]/Q -type DFF DFF
add mapped point quotient_q[31]/q quotient_q_reg[31]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[30]/q saved_op_b_abs_q_reg[30]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[31]/q saved_op_b_abs_q_reg[31]/Q -type DFF DFF
add mapped point saved_shift_amt_q[0]/q saved_shift_amt_q_reg[0]/Q -type DFF DFF
add mapped point saved_shift_amt_q[3]/q saved_shift_amt_q_reg[3]/Q -type DFF DFF
add mapped point saved_shift_amt_q[4]/q saved_shift_amt_q_reg[4]/Q -type DFF DFF
add mapped point saved_shift_amt_q[5]/q saved_shift_amt_q_reg[5]/Q -type DFF DFF
add mapped point wb_result_q[0]/q wb_result_q_reg[0]/Q -type DFF DFF
add mapped point wb_result_q[1]/q wb_result_q_reg[1]/Q -type DFF DFF
add mapped point wb_result_q[2]/q wb_result_q_reg[2]/Q -type DFF DFF
add mapped point wb_result_q[3]/q wb_result_q_reg[3]/Q -type DFF DFF
add mapped point wb_result_q[4]/q wb_result_q_reg[4]/Q -type DFF DFF
add mapped point wb_result_q[5]/q wb_result_q_reg[5]/Q -type DFF DFF
add mapped point wb_result_q[6]/q wb_result_q_reg[6]/Q -type DFF DFF
add mapped point wb_result_q[7]/q wb_result_q_reg[7]/Q -type DFF DFF
add mapped point wb_result_q[8]/q wb_result_q_reg[8]/Q -type DFF DFF
add mapped point wb_result_q[9]/q wb_result_q_reg[9]/Q -type DFF DFF
add mapped point wb_result_q[10]/q wb_result_q_reg[10]/Q -type DFF DFF
add mapped point wb_result_q[11]/q wb_result_q_reg[11]/Q -type DFF DFF
add mapped point wb_result_q[12]/q wb_result_q_reg[12]/Q -type DFF DFF
add mapped point wb_result_q[13]/q wb_result_q_reg[13]/Q -type DFF DFF
add mapped point wb_result_q[14]/q wb_result_q_reg[14]/Q -type DFF DFF
add mapped point wb_result_q[15]/q wb_result_q_reg[15]/Q -type DFF DFF
add mapped point wb_result_q[16]/q wb_result_q_reg[16]/Q -type DFF DFF
add mapped point wb_result_q[17]/q wb_result_q_reg[17]/Q -type DFF DFF
add mapped point wb_result_q[18]/q wb_result_q_reg[18]/Q -type DFF DFF
add mapped point wb_result_q[19]/q wb_result_q_reg[19]/Q -type DFF DFF
add mapped point wb_result_q[20]/q wb_result_q_reg[20]/Q -type DFF DFF
add mapped point wb_result_q[21]/q wb_result_q_reg[21]/Q -type DFF DFF
add mapped point wb_result_q[22]/q wb_result_q_reg[22]/Q -type DFF DFF
add mapped point wb_result_q[23]/q wb_result_q_reg[23]/Q -type DFF DFF
add mapped point wb_result_q[24]/q wb_result_q_reg[24]/Q -type DFF DFF
add mapped point wb_result_q[25]/q wb_result_q_reg[25]/Q -type DFF DFF
add mapped point wb_result_q[26]/q wb_result_q_reg[26]/Q -type DFF DFF
add mapped point wb_result_q[27]/q wb_result_q_reg[27]/Q -type DFF DFF
add mapped point wb_result_q[28]/q wb_result_q_reg[28]/Q -type DFF DFF
add mapped point wb_result_q[29]/q wb_result_q_reg[29]/Q -type DFF DFF
add mapped point wb_result_q[30]/q wb_result_q_reg[30]/Q -type DFF DFF
add mapped point wb_result_q[31]/q wb_result_q_reg[31]/Q -type DFF DFF
add mapped point divisor_q[0]/q divisor_q_reg[0]/Q -type DFF DFF
add mapped point divisor_q[1]/q divisor_q_reg[1]/Q -type DFF DFF
add mapped point divisor_q[2]/q divisor_q_reg[2]/Q -type DFF DFF
add mapped point divisor_q[3]/q divisor_q_reg[3]/Q -type DFF DFF
add mapped point divisor_q[5]/q divisor_q_reg[5]/Q -type DFF DFF
add mapped point divisor_q[11]/q divisor_q_reg[11]/Q -type DFF DFF
add mapped point divisor_q[15]/q divisor_q_reg[15]/Q -type DFF DFF
add mapped point divisor_q[17]/q divisor_q_reg[17]/Q -type DFF DFF
add mapped point divisor_q[22]/q divisor_q_reg[22]/Q -type DFF DFF
add mapped point divisor_q[25]/q divisor_q_reg[25]/Q -type DFF DFF
add mapped point divisor_q[27]/q divisor_q_reg[27]/Q -type DFF DFF
add mapped point last_a_q[29]/q last_a_q_reg[29]/Q -type DFF DFF
add mapped point op_a_abs_r[5]/q op_a_abs_r_reg[5]/Q -type DFF DFF
add mapped point op_a_abs_r[6]/q op_a_abs_r_reg[6]/Q -type DFF DFF
add mapped point op_a_abs_r[7]/q op_a_abs_r_reg[7]/Q -type DFF DFF
add mapped point op_a_abs_r[13]/q op_a_abs_r_reg[13]/Q -type DFF DFF
add mapped point op_a_abs_r[15]/q op_a_abs_r_reg[15]/Q -type DFF DFF
add mapped point op_b_abs_r[1]/q op_b_abs_r_reg[1]/Q -type DFF DFF
add mapped point op_b_abs_r[2]/q op_b_abs_r_reg[2]/Q -type DFF DFF
add mapped point op_b_abs_r[6]/q op_b_abs_r_reg[6]/Q -type DFF DFF
add mapped point op_b_abs_r[13]/q op_b_abs_r_reg[13]/Q -type DFF DFF
add mapped point op_b_abs_r[14]/q op_b_abs_r_reg[14]/Q -type DFF DFF
add mapped point op_b_abs_r[18]/q op_b_abs_r_reg[18]/Q -type DFF DFF
add mapped point op_b_abs_r[20]/q op_b_abs_r_reg[20]/Q -type DFF DFF
add mapped point op_b_abs_r[22]/q op_b_abs_r_reg[22]/Q -type DFF DFF
add mapped point op_b_abs_r[24]/q op_b_abs_r_reg[24]/Q -type DFF DFF
add mapped point op_b_abs_r[25]/q op_b_abs_r_reg[25]/Q -type DFF DFF
add mapped point op_b_abs_r[26]/q op_b_abs_r_reg[26]/Q -type DFF DFF
add mapped point op_b_abs_r[30]/q op_b_abs_r_reg[30]/Q -type DFF DFF
add mapped point op_b_abs_r[31]/q op_b_abs_r_reg[31]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[0]/q saved_op_b_abs_q_reg[0]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[1]/q saved_op_b_abs_q_reg[1]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[2]/q saved_op_b_abs_q_reg[2]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[3]/q saved_op_b_abs_q_reg[3]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[4]/q saved_op_b_abs_q_reg[4]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[5]/q saved_op_b_abs_q_reg[5]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[6]/q saved_op_b_abs_q_reg[6]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[7]/q saved_op_b_abs_q_reg[7]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[8]/q saved_op_b_abs_q_reg[8]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[9]/q saved_op_b_abs_q_reg[9]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[10]/q saved_op_b_abs_q_reg[10]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[11]/q saved_op_b_abs_q_reg[11]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[12]/q saved_op_b_abs_q_reg[12]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[13]/q saved_op_b_abs_q_reg[13]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[14]/q saved_op_b_abs_q_reg[14]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[15]/q saved_op_b_abs_q_reg[15]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[16]/q saved_op_b_abs_q_reg[16]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[17]/q saved_op_b_abs_q_reg[17]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[18]/q saved_op_b_abs_q_reg[18]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[19]/q saved_op_b_abs_q_reg[19]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[20]/q saved_op_b_abs_q_reg[20]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[21]/q saved_op_b_abs_q_reg[21]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[22]/q saved_op_b_abs_q_reg[22]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[23]/q saved_op_b_abs_q_reg[23]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[24]/q saved_op_b_abs_q_reg[24]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[25]/q saved_op_b_abs_q_reg[25]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[26]/q saved_op_b_abs_q_reg[26]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[27]/q saved_op_b_abs_q_reg[27]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[28]/q saved_op_b_abs_q_reg[28]/Q -type DFF DFF
add mapped point saved_op_b_abs_q[29]/q saved_op_b_abs_q_reg[29]/Q -type DFF DFF
add mapped point saved_shift_amt_q[1]/q saved_shift_amt_q_reg[1]/Q -type DFF DFF
add mapped point saved_shift_amt_q[2]/q saved_shift_amt_q_reg[2]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
